apiVersion: apps/v1
kind: Deployment
metadata:
  name: feedback
  labels:
    app: feedback
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: feedback
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: feedback
    spec:
      initContainers:
      - name: init-permissions
        image: busybox
        command: ['sh', '-c', 'chown -R 1000:1000 /data']
        volumeMounts:
        - name: feedback-storage
          mountPath: /data
      containers:
      - name: feedback
        image: localhost:5001/feedback:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        envFrom:
        - configMapRef:
            name: feedback-env
        volumeMounts:
        - name: feedback-storage
          mountPath: /data
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
      terminationGracePeriodSeconds: 180
      volumes:
      - name: feedback-storage
        persistentVolumeClaim:
          claimName: feedback-pvc
