---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: onlyoffice
  labels:
    app: onlyoffice
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: onlyoffice
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: onlyoffice
    spec:
      hostNetwork: true
      containers:
      - name: onlyoffice
        image: localhost:5001/onlyoffice:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        - name: r7-api
          containerPort: 22200
        envFrom:
        - configMapRef:
            name: onlyoffice-env
        securityContext:
          runAsUser: 0    # Запуск от имени пользователя root
          runAsGroup: 0   # Группа root
          allowPrivilegeEscalation: true
      terminationGracePeriodSeconds: 180