---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    app: server
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: localhost:5001/server:latest
        imagePullPolicy: Always
        volumeMounts:
        - name: config
          mountPath: "/etc/config"
          readOnly: true
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        envFrom:
        - configMapRef:
            name: server-env
        securityContext:
          runAsUser: 0    # Запуск от имени пользователя root
          runAsGroup: 0   # Группа root
          allowPrivilegeEscalation: true
      terminationGracePeriodSeconds: 180
      volumes:
      - name: config
        configMap:
          name: cards-config